### ISSUE TITLE
fill in the README.md

### ISSUE THREAD

**Issue by VinterSallad** [VinterSallad/ci-server-group11#2]

**Comment by VinterSallad** [comment]
Statement of contribution:

Alexander: Setting up the repo and server skeleton (Initial Meeting). Running and Testing the server. Entrypoint for the server, i.e. handling the GitHub JSON POST request. Creating and initialising test file and JSON tests.

**Comment by MercuriaL01** [comment]
Statement of contribution:

Iley: I added support for notifications of CI results and tests for it, by using the REST API for Github. I also reviewed one of Roxanne's pull requests.
